"""Added name column to cart table

Revision ID: 3d968c7ab0a1
Revises: 5ddd76528329
Create Date: 2021-10-21 10:06:55.566254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d968c7ab0a1'
down_revision = '5ddd76528329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('name', sa.String(length=32), nullable=True))
    op.add_column('item', sa.Column('low_stock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'low_stock')
    op.drop_column('cart', 'name')
    # ### end Alembic commands ###
