"""Added post restock count to help keep track of amount before stock was low

Revision ID: 5ddd76528329
Revises: e9fae499af89
Create Date: 2021-10-21 09:59:32.004858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddd76528329'
down_revision = 'e9fae499af89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('post_restock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'post_restock')
    # ### end Alembic commands ###
